// nextjsFrontend/directmethod/components/sections/Hero.tsx
import Image from 'next/image';
import { Button } from '../ui/Button';

export default function Hero() {
  return (
    <section id="hero" className="min-h-screen flex items-center px-8 py-16 bg-light-yellow">
      <div className="max-w-7xl mx-auto w-full grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
        {/* Left content */}
        <div className="space-y-8">
          <div className="space-y-4">
            <h2 className="text-3xl md:text-4xl font-medium text-dark-blue">
              Hello, I'm John,
            </h2>
            <h1 className="text-6xl md:text-8xl lg:text-9xl font-extrabold text-dark-blue leading-tight">
              Product Designer
            </h1>
            <h3 className="text-3xl md:text-4xl font-medium text-dark-blue">
              based in Netherland.
            </h3>
          </div>
          
          <div className="flex items-center gap-4">
            {/* Decorative elements */}
            <div className="flex gap-1">
              {[...Array(5)].map((_, i) => (
                <div
                  key={i}
                  className="w-4 h-8 bg-dark-brown rounded-sm"
                />
              ))}
            </div>
          </div>
          
          <Button variant="primary" size="lg">
            Resume
          </Button>
        </div>
        
        {/* Right content - Profile image */}
        <div className="flex justify-center lg:justify-end">
          <div className="relative">
            <div className="relative w-80 h-96 md:w-96 md:h-[500px] overflow-hidden rounded-2xl border-4 border-dark-brown">
              <Image
                src="/images/profile-image.png"
                alt="John Doe - Product Designer"
                fill
                className="object-cover"
                priority
              />
            </div>
            
            {/* Decorative plus signs */}
            <div className="absolute -top-6 -right-6 flex flex-col gap-4">
              <div className="flex gap-4">
                <div className="w-6 h-6 relative bg-transparent rounded-md border-2 border-dark-brown">
                  <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-1 h-4 bg-dark-brown rounded-sm"></div>
                  <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-4 h-1 bg-dark-brown rounded-sm"></div>
                </div>
                <div className="w-6 h-6 relative bg-transparent rounded-md border-2 border-dark-brown">
                  <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-1 h-4 bg-dark-brown rounded-sm"></div>
                  <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-4 h-1 bg-dark-brown rounded-sm"></div>
                </div>
              </div>
              <div className="flex gap-4">
                <div className="w-6 h-6 relative bg-transparent rounded-md border-2 border-dark-brown">
                  <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-1 h-4 bg-dark-brown rounded-sm"></div>
                  <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-4 h-1 bg-dark-brown rounded-sm"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// svelteKitFrontend/directMethod/src/lib/components/Hero.svelte
<script lang="ts">
	import Button from './Button.svelte';
	import profileImage from '$lib/assets/profile-image.png';
</script>

<section id="home" class="hero">
	<div class="container">
		<div class="hero-content">
			<div class="hero-text">
				<p class="greeting">Hello, I'm John,</p>
				<h1 class="title">Product Designer</h1>
				<p class="location">based in Netherland.</p>
				
				<div class="decorative-bars">
					<div class="bar"></div>
					<div class="bar"></div>
					<div class="bar"></div>
					<div class="bar"></div>
					<div class="bar"></div>
				</div>
				
				<Button variant="primary" href="#contact">Resume</Button>
			</div>
			
			<div class="hero-image">
				<div class="image-container">
					<img src={profileImage} alt="John Doe - Product Designer" />
					<div class="decorative-elements">
						<div class="plus-icons">
							<div class="plus-icon">
								<div class="plus-horizontal"></div>
								<div class="plus-vertical"></div>
							</div>
							<div class="plus-icon">
								<div class="plus-horizontal"></div>
								<div class="plus-vertical"></div>
							</div>
							<div class="plus-icon">
								<div class="plus-horizontal"></div>
								<div class="plus-vertical"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<style>
	.hero {
		min-height: 100vh;
		background: #fbf8cc;
		padding: 6rem 0 4rem 0;
		display: flex;
		align-items: center;
	}

	.container {
		max-width: 1200px;
		margin: 0 auto;
		padding: 0 2rem;
		width: 100%;
	}

	.hero-content {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 4rem;
		align-items: center;
	}

	.hero-text {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.greeting {
		font-family: 'Poppins', sans-serif;
		font-weight: 500;
		font-size: 1.75rem;
		color: #03045e;
		margin: 0;
		line-height: 1.5;
	}

	.title {
		font-family: 'Poppins', sans-serif;
		font-weight: 800;
		font-size: 6.25rem;
		color: #03045e;
		margin: 0;
		line-height: 1.16;
	}

	.location {
		font-family: 'Poppins', sans-serif;
		font-weight: 500;
		font-size: 1.75rem;
		color: #03045e;
		margin: 0 0 2rem 0;
		line-height: 1.5;
	}

	.decorative-bars {
		display: flex;
		gap: 0.5rem;
		margin: 2rem 0;
	}

	.bar {
		width: 16px;
		height: 29px;
		background: #474306;
		border-radius: 6px;
	}

	.hero-image {
		display: flex;
		justify-content: center;
		position: relative;
	}

	.image-container {
		position: relative;
		max-width: 400px;
		width: 100%;
	}

	.image-container img {
		width: 100%;
		height: auto;
		border-radius: 12px;
		border: 1px solid #474306;
	}

	.decorative-elements {
		position: absolute;
		top: -20px;
		right: -20px;
	}

	.plus-icons {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 8px;
	}

	.plus-icon {
		position: relative;
		width: 24px;
		height: 24px;
		background: rgba(251, 248, 204, 0.9);
		border-radius: 6px;
		border: 1px solid #474306;
	}

	.plus-horizontal,
	.plus-vertical {
		position: absolute;
		background: #474306;
		border-radius: 6px;
	}

	.plus-horizontal {
		width: 24px;
		height: 6px;
		top: 50%;
		left: 0;
		transform: translateY(-50%);
	}

	.plus-vertical {
		width: 6px;
		height: 24px;
		left: 50%;
		top: 0;
		transform: translateX(-50%);
	}

	@media (max-width: 1024px) {
		.title {
			font-size: 5rem;
		}
	}

	@media (max-width: 768px) {
		.hero {
			padding: 5rem 0 3rem 0;
		}

		.container {
			padding: 0 1rem;
		}

		.hero-content {
			grid-template-columns: 1fr;
			gap: 3rem;
			text-align: center;
		}

		.greeting,
		.location {
			font-size: 1.5rem;
		}

		.title {
			font-size: 3.5rem;
		}

		.decorative-bars {
			justify-content: center;
		}

		.decorative-elements {
			top: -15px;
			right: -15px;
		}

		.plus-icon {
			width: 20px;
			height: 20px;
		}

		.plus-horizontal {
			width: 20px;
			height: 5px;
		}

		.plus-vertical {
			width: 5px;
			height: 20px;
		}
	}
</style>
