// frontendOutput/src/components/Work.tsx
import Image from 'next/image'

const projects = [
  {
    title: "Some Case Study",
    date: "November 24, 2019",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed aliquam sollicitudin rhoncus morbi. Tincidunt quam sem elit a convallis. Eget ipsum, velit vitae eu nunc, consequat, at.",
    image: "/images/project1-image.png"
  },
  {
    title: "Some Case Study",
    date: "November 24, 2019", 
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed aliquam sollicitudin rhoncus morbi. Tincidunt quam sem elit a convallis. Eget ipsum, velit vitae eu nunc, consequat, at.",
    image: "/images/project2-image.png"
  }
]

export default function Work() {
  return (
    <section id="work" className="py-16 lg:py-24">
      <div className="space-y-16">
        {/* Work Title */}
        <h2 className="text-6xl lg:text-8xl font-extrabold text-accent leading-tight">
          work.
        </h2>

        {/* Work Description */}
        <div className="max-w-4xl">
          <p className="text-2xl text-primary leading-relaxed">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. 
            Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam.
          </p>
        </div>

        {/* Projects Grid */}
        <div className="grid lg:grid-cols-2 gap-16">
          {projects.map((project, index) => (
            <div key={index} className="space-y-6">
              {/* Project Image */}
              <div className="relative aspect-[4/3] w-full">
                <Image
                  src={project.image}
                  alt={project.title}
                  fill
                  className="object-cover rounded-lg"
                />
              </div>
              
              {/* Project Details */}
              <div className="space-y-4">
                <p className="text-sm text-primary opacity-80">
                  {project.date}
                </p>
                <h3 className="text-2xl font-semibold text-primary">
                  {project.title}
                </h3>
                <p className="text-lg text-primary leading-relaxed">
                  {project.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

// angularFrontend/directMethod/src/app/components/work/work.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-work',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './work.component.html',
  styleUrls: ['./work.component.scss']
})
export class WorkComponent {
  workData = {
    title: 'work.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam.',
    projects: [
      {
        id: 1,
        title: 'Some Case Study',
        date: 'November 24, 2019',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed aliquam sollicitudin rhoncus morbi. Tincidunt quam sem elit a convallis. Eget ipsum, velit vitae eu nunc, consequat, at.',
        image: 'assets/images/project1.png',
        link: '#'
      },
      {
        id: 2,
        title: 'Some Case Study',
        date: 'November 24, 2019',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed aliquam sollicitudin rhoncus morbi. Tincidunt quam sem elit a convallis. Eget ipsum, velit vitae eu nunc, consequat, at.',
        image: 'assets/images/project2.png',
        link: '#'
      }
    ]
  };
}

<section class="work" id="work">
  <div class="container">
    <div class="work__content">
      <!-- Titre de section -->
      <h2 class="work__title heading-primary accent-text">{{ workData.title }}</h2>
      
      <!-- Description principale -->
      <div class="work__description">
        <p class="text-body">{{ workData.description }}</p>
      </div>

      <!-- Grille des projets -->
      <div class="work__projects">
        @for (project of workData.projects; track project.id) {
          <article class="project-card">
            <div class="project-card__image">
              <img 
                [src]="project.image" 
                [alt]="project.title"
                class="project-image"
              />
            </div>
            <div class="project-card__content">
              <time class="project-date text-tiny">{{ project.date }}</time>
              <h3 class="project-title heading-tertiary">{{ project.title }}</h3>
              <p class="project-description text-small">{{ project.description }}</p>
              <a [href]="project.link" class="project-link">
                Voir le projet
                <span class="sr-only">{{ project.title }}</span>
              </a>
            </div>
          </article>
        }
      </div>
    </div>
  </div>
</section>
