// generationBenchFrontend/simple/ByClaude4Sonnet/angular/directMethod/src/app/components/about/about.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss']
})
export class AboutComponent {
  aboutData = {
    title: 'about.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam.',
    experiences: [
      {
        period: '2014-2018',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam.'
      },
      {
        period: '2018-2020',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam.'
      },
      {
        period: '2020 - Present',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam.'
      }
    ]
  };
}

<section class="about" id="about">
  <div class="container">
    <div class="about__content">
      <!-- Titre de section -->
      <h2 class="about__title heading-primary accent-text">{{ aboutData.title }}</h2>
      
      <!-- Description principale -->
      <div class="about__description">
        <p class="text-body">{{ aboutData.description }}</p>
      </div>

      <!-- Timeline des expériences -->
      <div class="about__timeline">
        @for (experience of aboutData.experiences; track experience.period; let index = $index) {
          <div class="timeline-item" [class.timeline-item--active]="index === 0">
            <div class="timeline-marker">
              <div class="timeline-dot"></div>
            </div>
            <div class="timeline-content">
              <h3 class="timeline-period heading-tertiary">{{ experience.period }}</h3>
              <p class="timeline-description text-body">{{ experience.description }}</p>
            </div>
          </div>
        }
      </div>
    </div>
  </div>
</section>

// frontendOutput/src/components/About.tsx
export default function About() {
  return (
    <section id="about" className="py-16 lg:py-24">
      <div className="space-y-12">
        {/* About Title */}
        <h2 className="text-6xl lg:text-8xl font-extrabold text-accent leading-tight">
          about.
        </h2>

        {/* About Content */}
        <div className="max-w-4xl">
          <p className="text-2xl text-primary leading-relaxed">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. 
            Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam.
          </p>
        </div>
      </div>
    </section>
  )
}
