// generationBenchFrontend/simple/ByClaude4Sonnet/svelteKit/directMethod/src/lib/components/Header.svelte
<script lang="ts">
	import SocialIcons from './SocialIcons.svelte';
</script>

<header class="header">
	<div class="container">
		<div class="nav-brand">
			<h1 class="name">John Doe</h1>
		</div>
		
		<nav class="navigation">
			<a href="#home" class="nav-link">Home</a>
			<a href="#about" class="nav-link">About</a>
			<a href="#work" class="nav-link">Work</a>
		</nav>
		
		<SocialIcons />
	</div>
</header>

<style>
	.header {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		background: #fbf8cc;
		z-index: 1000;
		padding: 1rem 0;
		border-bottom: 1px solid #03045e;
	}

	.container {
		max-width: 1200px;
		margin: 0 auto;
		padding: 0 2rem;
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.name {
		font-family: 'Poppins', sans-serif;
		font-weight: 600;
		font-size: 1.5rem;
		color: #03045e;
		margin: 0;
	}

	.navigation {
		display: flex;
		gap: 2rem;
	}

	.nav-link {
		font-family: 'Poppins', sans-serif;
		font-weight: 400;
		font-size: 1.125rem;
		color: #03045e;
		text-decoration: none;
		transition: color 0.3s ease;
	}

	.nav-link:hover {
		color: #474306;
	}

	@media (max-width: 768px) {
		.container {
			padding: 0 1rem;
		}
		
		.navigation {
			gap: 1rem;
		}
		
		.nav-link {
			font-size: 1rem;
		}
	}
</style>

// frontendOutput/src/components/Header.tsx
import Image from 'next/image'

export default function Header() {
  return (
    <header className="w-full max-w-6xl mx-auto px-6 py-6">
      <div className="flex justify-between items-center">
        {/* Logo/Name */}
        <div className="text-2xl font-semibold text-primary">
          John Doe
        </div>

        {/* Navigation */}
        <nav className="hidden md:flex items-center space-x-8">
          <a href="#home" className="text-primary hover:text-secondary transition-colors">
            Home
          </a>
          <a href="#about" className="text-primary hover:text-secondary transition-colors">
            About
          </a>
          <a href="#work" className="text-primary hover:text-secondary transition-colors">
            Work
          </a>
        </nav>

        {/* Social Icons */}
        <div className="flex items-center space-x-4">
          <a href="#" className="text-primary hover:text-secondary transition-colors">
            <svg width="26" height="16" viewBox="0 0 26 16" fill="currentColor">
              <path d="M13 0C8.6 0 5 3.6 5 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm0 14c-3.3 0-6-2.7-6-6s2.7-6 6-6 6 2.7 6 6-2.7 6-6 6z"/>
            </svg>
          </a>
          <a href="#" className="text-primary hover:text-secondary transition-colors">
            <svg width="26" height="18" viewBox="0 0 26 18" fill="currentColor">
              <path d="M23.3 4.4c0-.2 0-.4-.1-.6v-.1c-.6-2.3-2.4-4.1-4.7-4.7h-.1c-.2 0-.4-.1-.6-.1-1.5-.1-3-.1-4.5-.1s-3 0-4.5.1c-.2 0-.4 0-.6.1h-.1c-2.3.6-4.1 2.4-4.7 4.7v.1c0 .2-.1.4-.1.6-.1 1.5-.1 3-.1 4.5s0 3 .1 4.5c0 .2 0 .4.1.6v.1c.6 2.3 2.4 4.1 4.7 4.7h.1c.2 0 .4.1.6.1 1.5.1 3 .1 4.5.1s3 0 4.5-.1c.2 0 .4 0 .6-.1h.1c2.3-.6 4.1-2.4 4.7-4.7v-.1c0-.2.1-.4.1-.6.1-1.5.1-3 .1-4.5s0-3-.1-4.5z"/>
            </svg>
          </a>
          <a href="#" className="text-primary hover:text-secondary transition-colors">
            <svg width="26" height="15" viewBox="0 0 26 15" fill="currentColor">
              <path d="M13 0C6.4 0 1 6.7 1 15h24c0-8.3-5.4-15-12-15z"/>
            </svg>
          </a>
        </div>
      </div>
    </header>
  )
}
