// front/src/App.svelte
<script>
  import { auditState, showReport, hasComponentSuggestions, getComponentSuggestions, getFigmaAiDescription } from './stores/audit.svelte.js';
  import InputForm from './lib/forms/InputForm.svelte';
  import LoadingSpinner from './lib/common/LoadingSpinner.svelte';
  import ErrorDisplay from './lib/common/ErrorDisplay.svelte';
  import StatsCards from './lib/display/StatsCards.svelte';
  import TotalDetectedRules from './lib/display/TotalDetectedRules.svelte';
  import FigmaDescription from './lib/display/FigmaDescription.svelte';
  import DesignSystemViewer from './lib/display/DesignSystemViewer.svelte';
  import DetailedTables from './lib/display/DetailedTables.svelte';
  import ComponentSuggestionsCards from './lib/display/ComponentSuggestionsCards.svelte';

  // Titre intégré (pas de composant séparé selon les specs)
  const title = 'FigmAnalyse de maquette';
  const subtitle = 'Analysez vos designs Figma selon les meilleures pratiques';

  // Message NoReportGenerated intégré (pas de composant séparé)
  const noReportMessage = 'Aucun rapport généré pour le moment';
  const noReportSubtext = 'Entrez une URL Figma ci-dessus pour commencer l\'audit de votre design';
</script>

<div class="min-h-screen bg-figma-background">
  <div class="w-full px-8 py-12">
    <!-- Titre intégré -->
    <header class="text-center mb-12">
      <h1 class="text-4xl font-bold text-white mb-4">
        {title}
      </h1>
    </header>

    <!-- Formulaire toujours visible selon les specs -->
    <section class="mb-8">
      <InputForm />
    </section>

    <!-- États conditionnels -->
    {#if auditState.error}
      <ErrorDisplay />
    {:else if auditState.isLoading}
      <LoadingSpinner />
    {:else if showReport()}
      <!-- Mode rapport -->
      <div class="space-y-8">
        <!-- Règles détectées et description côte à côte -->
        <div class="flex flex-col lg:flex-row gap-6">
          <div class="flex-1">
            <TotalDetectedRules />
          </div>
          <div class="flex-1">
            <FigmaDescription description={getFigmaAiDescription()} />
          </div>
        </div>

        <!-- Design System Viewer -->
        <DesignSystemViewer />

        <!-- Component Suggestions (si disponibles) -->
        {#if hasComponentSuggestions()}
          <ComponentSuggestionsCards
            componentSuggestions={getComponentSuggestions()}
            baseFigmaUrl={auditState.figmaUrl}
          />
        {/if}

        <!-- cartes statistiques en haut -->
        <StatsCards />
        
        <!-- Rapport d'analyse prend toute la largeur -->
        <div class="w-full">
          <DetailedTables />
        </div>
      </div>
    {:else}
      <!-- État initial - NoReportGenerated intégré -->
      <section class="text-center py-16 w-full">
        <h2 class="text-2xl font-semibold text-white mb-6">
          {noReportMessage}
        </h2>
      </section>
    {/if}
  </div>
</div>

<style>
</style>

// front/src/App.tsx
import React from 'react';
import { useAudit } from './contexts/AuditContext';
import InputForm from './components/forms/InputForm';
import LoadingSpinner from './components/common/LoadingSpinner';
import ErrorDisplay from './components/common/ErrorDisplay';
import StatsCards from './components/display/StatsCards';
import TotalDetectedRules from './components/display/TotalDetectedRules';
import FigmaDescription from './components/display/FigmaDescription';
import DesignSystemViewer from './components/display/DesignSystemViewer';
import DetailedTables from './components/display/DetailedTables';
import ComponentSuggestionsCards from './components/display/ComponentSuggestionsCards';

const App: React.FC = () => {
  const { state, showReport, hasComponentSuggestions, getComponentSuggestions, getFigmaAiDescription } = useAudit();

  // Titre intégré (pas de composant séparé selon les specs)
  const title = 'FigmAnalyse de maquette';

  // Message NoReportGenerated intégré (pas de composant séparé)
  const noReportMessage = 'Aucun rapport généré pour le moment';

  return (
    <div className="min-h-screen bg-figma-background">
      <div className="w-full px-8 py-12">
        {/* Titre intégré */}
        <header className="text-center mb-12">
          <h1 className="text-4xl font-bold text-white mb-4">
            {title}
          </h1>
        </header>

        {/* Formulaire toujours visible selon les specs */}
        <section className="mb-8">
          <InputForm />
        </section>

        {/* États conditionnels */}
        {state.error ? (
          <ErrorDisplay />
        ) : state.isLoading ? (
          <LoadingSpinner />
        ) : showReport() ? (
          /* Mode rapport */
          <div className="space-y-8">
            {/* Règles détectées et description côte à côte */}
            <div className="flex flex-col lg:flex-row gap-6">
              <div className="flex-1">
                <TotalDetectedRules />
              </div>
              <div className="flex-1">
                <FigmaDescription description={getFigmaAiDescription()} />
              </div>
            </div>

            {/* Design System Viewer */}
            <DesignSystemViewer />

            {/* Component Suggestions (si disponibles) */}
            {hasComponentSuggestions() && (
              <ComponentSuggestionsCards
                componentSuggestions={getComponentSuggestions()}
                baseFigmaUrl={state.figmaUrl}
              />
            )}

            {/* cartes statistiques en haut */}
            <StatsCards />

            {/* Rapport d'analyse prend toute la largeur */}
            <div className="w-full">
              <DetailedTables />
            </div>
          </div>
        ) : (
          /* État initial - NoReportGenerated intégré */
          <section className="text-center py-16 w-full">
            <h2 className="text-2xl font-semibold text-white mb-6">
              {noReportMessage}
            </h2>
          </section>
        )}
      </div>
    </div>
  );
};

export default App;
