// svelteKitFrontendOptimised/src/lib/components/Header.svelte
<script lang="ts">
  import SocialIcons from './SocialIcons.svelte';

  interface Props {
    name?: string;
  }

  let { name = 'John Doe' }: Props = $props();
</script>

<!-- Header: 1246x36px avec layout row, space-between, center -->
<header class="w-[1246px] h-[36px] flex justify-between items-center gap-[10px]">
  
  <!-- Logo/Name: 114x36px -->
  <div class="w-[114px] h-[36px] flex items-center">
    <h1 class="font-poppins font-semibold text-name text-dark-blue leading-relaxed-custom">
      {name}
    </h1>
  </div>

  <!-- Navigation Menu: 276x27px avec gap 61px -->
  <nav class="w-[276px] h-[27px] flex justify-center items-center gap-[61px]">
    <a 
      href="#home" 
      class="w-[54px] h-[27px] font-poppins font-normal text-body-small text-dark-blue leading-relaxed-custom hover:opacity-70 transition-opacity flex items-center"
    >
      Home
    </a>
    <a 
      href="#about" 
      class="w-[54px] h-[27px] font-poppins font-normal text-body-small text-dark-blue leading-relaxed-custom hover:opacity-70 transition-opacity flex items-center"
    >
      About
    </a>
    <a 
      href="#work" 
      class="w-[46px] h-[27px] font-poppins font-normal text-body-small text-dark-blue leading-relaxed-custom hover:opacity-70 transition-opacity flex items-center"
    >
      Work
    </a>
  </nav>

  <!-- Social Media Icons: 98x17.8px -->
  <div class="w-[98px] h-[18px] flex items-center">
    <SocialIcons />
  </div>
  
</header>

// nextjsFrontend/directmethod/components/layout/Header.tsx
import Image from 'next/image';
import Navigation from './Navigation';

export default function Header() {
  return (
    <header className="w-full py-4 px-8 flex justify-between items-center bg-light-yellow">
      <div className="flex items-center">
        <h1 className="text-2xl font-semibold text-dark-blue">John Doe</h1>
      </div>
      
      <Navigation className="hidden md:flex" />
      
      <div className="flex items-center gap-4">
        <a 
          href="https://medium.com/johndoe" 
          target="_blank" 
          rel="noopener noreferrer"
          className="hover:opacity-70 transition-opacity"
        >
          <Image
            src="/images/medium-icon.svg"
            alt="Medium"
            width={26}
            height={15}
            className="text-dark-blue"
          />
        </a>
        <a 
          href="https://behance.net/johndoe" 
          target="_blank" 
          rel="noopener noreferrer"
          className="hover:opacity-70 transition-opacity"
        >
          <Image
            src="/images/behance-icon.svg"
            alt="Behance"
            width={26}
            height={17}
            className="text-dark-blue"
          />
        </a>
        <a 
          href="https://twitter.com/johndoe" 
          target="_blank" 
          rel="noopener noreferrer"
          className="hover:opacity-70 transition-opacity"
        >
          <Image
            src="/images/twitter-icon.svg"
            alt="Twitter"
            width={20}
            height={16}
            className="text-dark-blue"
          />
        </a>
      </div>
    </header>
  );
}
