// generationBenchFrontend/simple/ByClaude4Sonnet/nextjs/directmethod/components/sections/About.tsx
export default function About() {
  const experiences = [
    {
      period: "2014-2018",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam."
    },
    {
      period: "2018-2020", 
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam."
    },
    {
      period: "2020 - Present",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam."
    }
  ];

  return (
    <section id="about" className="py-16 px-8 bg-light-yellow">
      <div className="max-w-7xl mx-auto">
        {/* Section title */}
        <h2 className="text-6xl md:text-8xl lg:text-9xl font-extrabold text-too-light-yellow mb-12">
          about.
        </h2>
        
        {/* About description */}
        <div className="mb-16">
          <p className="text-xl md:text-2xl text-dark-blue leading-relaxed max-w-4xl">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. 
            Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam.
          </p>
        </div>
        
        {/* Timeline */}
        <div className="space-y-12">
          {experiences.map((experience, index) => (
            <div key={index} className="flex gap-8 items-start">
              {/* Timeline bullet */}
              <div className="flex flex-col items-center">
                <div className="w-3 h-3 bg-dark-blue rounded-full mt-2"></div>
                {index < experiences.length - 1 && (
                  <div className="w-0.5 h-20 bg-dark-blue opacity-30 mt-4"></div>
                )}
              </div>
              
              {/* Content */}
              <div className="flex-1 space-y-4">
                <h3 className="text-2xl font-semibold text-dark-blue">
                  {experience.period}
                </h3>
                <p className="text-xl text-dark-blue leading-relaxed max-w-4xl">
                  {experience.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// generationBenchFrontend/simple/ByClaude4Sonnet/svelteKit/directMethod/src/lib/components/About.svelte
<script lang="ts">
	interface TimelineItem {
		period: string;
		description: string;
	}

	const timelineData: TimelineItem[] = [
		{
			period: "2014-2018",
			description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam."
		},
		{
			period: "2018-2020",
			description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam."
		},
		{
			period: "2020 - Present",
			description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam."
		}
	];
</script>

<section id="about" class="about">
	<div class="container">
		<h2 class="section-title">about.</h2>
		
		<p class="intro-text">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. 
			Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam.
		</p>
		
		<div class="timeline">
			{#each timelineData as item, index}
				<div class="timeline-item">
					<div class="timeline-marker">
						<div class="dot"></div>
					</div>
					<div class="timeline-content">
						<h3 class="period">{item.period}</h3>
						<p class="description">{item.description}</p>
					</div>
				</div>
			{/each}
		</div>
	</div>
</section>

<style>
	.about {
		background: #fbf8cc;
		padding: 6rem 0;
	}

	.container {
		max-width: 1200px;
		margin: 0 auto;
		padding: 0 2rem;
	}

	.section-title {
		font-family: 'Poppins', sans-serif;
		font-weight: 800;
		font-size: 6.25rem;
		color: #f7f197;
		margin: 0 0 3rem 0;
		line-height: 1.16;
	}

	.intro-text {
		font-family: 'Poppins', sans-serif;
		font-weight: 400;
		font-size: 1.5rem;
		color: #03045e;
		line-height: 1.833;
		margin: 0 0 4rem 0;
		max-width: 900px;
	}

	.timeline {
		position: relative;
		max-width: 900px;
		margin-left: 2rem;
	}

	.timeline::before {
		content: '';
		position: absolute;
		left: -2rem;
		top: 0;
		bottom: 0;
		width: 2px;
		background: #03045e;
	}

	.timeline-item {
		position: relative;
		margin-bottom: 3rem;
		display: flex;
		align-items: flex-start;
		gap: 2rem;
	}

	.timeline-item:last-child {
		margin-bottom: 0;
	}

	.timeline-marker {
		position: absolute;
		left: -2.5rem;
		top: 0.5rem;
		width: 13px;
		height: 13px;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.dot {
		width: 13px;
		height: 13px;
		background: #03045e;
		border-radius: 50%;
	}

	.timeline-content {
		flex: 1;
	}

	.period {
		font-family: 'Poppins', sans-serif;
		font-weight: 600;
		font-size: 1.5rem;
		color: #03045e;
		margin: 0 0 1rem 0;
		line-height: 1.667;
	}

	.description {
		font-family: 'Poppins', sans-serif;
		font-weight: 400;
		font-size: 1.5rem;
		color: #03045e;
		line-height: 1.833;
		margin: 0;
	}

	@media (max-width: 1024px) {
		.section-title {
			font-size: 5rem;
		}
	}

	@media (max-width: 768px) {
		.about {
			padding: 4rem 0;
		}

		.container {
			padding: 0 1rem;
		}

		.section-title {
			font-size: 3.5rem;
			margin-bottom: 2rem;
		}

		.intro-text {
			font-size: 1.25rem;
			margin-bottom: 3rem;
		}

		.timeline {
			margin-left: 1.5rem;
		}

		.timeline::before {
			left: -1.5rem;
		}

		.timeline-marker {
			left: -2rem;
		}

		.period {
			font-size: 1.25rem;
		}

		.description {
			font-size: 1.25rem;
		}

		.timeline-item {
			margin-bottom: 2.5rem;
		}
	}
</style>
