// frontend-output-corrected/src/components/Hero.tsx
import React from 'react';
import Image from 'next/image';

const Hero = () => {
  return (
    <section className="w-full px-4 md:px-[97px]">
      <div className="flex flex-col md:flex-row justify-between items-center w-full max-w-[1246px] mx-auto min-h-[509px] gap-8 md:gap-0">
        {/* Texte descriptif */}
        <div className="flex flex-col justify-center gap-[10px] w-full md:w-[616px] text-center md:text-left">
          <h1 className="text-secondary text-xl md:text-[28px] font-medium leading-[1.5]">
            Hello, I'm John,
          </h1>
          
          <h2 className="text-secondary text-4xl sm:text-6xl md:text-[100px] font-extrabold leading-[1.16]">
            Product Designer
          </h2>
          
          <p className="text-secondary text-xl md:text-[28px] font-medium leading-[1.5]">
            based in Netherland.
          </p>
        </div>

        {/* Image de profil */}
        <div className="relative w-64 h-64 md:w-[506px] md:h-[509px] flex-shrink-0">
          <div className="absolute inset-0 w-full h-full md:w-[493px] md:h-[493px] md:top-0 md:left-[13px] overflow-hidden rounded-lg md:rounded-none">
            <Image
              src="/images/profile-photo.png"
              alt="John Doe Profile"
              fill
              className="object-cover"
              priority
            />
          </div>
          {/* Bordure SVG - Hidden on mobile */}
          <div className="hidden md:block absolute w-[493px] h-[493px] top-[16px] left-0">
            <svg viewBox="0 0 493 493" fill="none" className="w-full h-full">
              <rect 
                x="0.5" 
                y="0.5" 
                width="492" 
                height="492" 
                stroke="#000000" 
                strokeWidth="1"
              />
            </svg>
          </div>
        </div>
      </div>

      {/* Bouton Resume */}
      <div className="w-full max-w-[1246px] mx-auto mt-4 md:mt-[10px] flex justify-center md:justify-start">
        <button className="relative w-[164px] h-[68px] group">
          {/* Background */}
          <div className="absolute top-[7px] left-[6px] w-[158px] h-[61px] bg-primary-dark rounded-[6px]"></div>
          
          {/* Bordure */}
          <div className="absolute top-0 left-0 w-[158px] h-[61px] border border-secondary-dark rounded-[6px] bg-transparent group-hover:bg-primary-dark transition-colors"></div>
          
          {/* Texte */}
          <span className="absolute top-[16px] left-[38px] text-secondary-dark text-[20px] font-normal leading-[1.5] w-[81px] h-[30px] flex items-center justify-center">
            Resume
          </span>
        </button>
      </div>
    </section>
  );
};

export default Hero;

// generationBenchFrontend/simple/ByClaude4Sonnet/svelteKit/directMethod/src/lib/components/Hero.svelte
<script lang="ts">
	import Button from './Button.svelte';
	import profileImage from '$lib/assets/profile-image.png';
</script>

<section id="home" class="hero">
	<div class="container">
		<div class="hero-content">
			<div class="hero-text">
				<p class="greeting">Hello, I'm John,</p>
				<h1 class="title">Product Designer</h1>
				<p class="location">based in Netherland.</p>
				
				<div class="decorative-bars">
					<div class="bar"></div>
					<div class="bar"></div>
					<div class="bar"></div>
					<div class="bar"></div>
					<div class="bar"></div>
				</div>
				
				<Button variant="primary" href="#contact">Resume</Button>
			</div>
			
			<div class="hero-image">
				<div class="image-container">
					<img src={profileImage} alt="John Doe - Product Designer" />
					<div class="decorative-elements">
						<div class="plus-icons">
							<div class="plus-icon">
								<div class="plus-horizontal"></div>
								<div class="plus-vertical"></div>
							</div>
							<div class="plus-icon">
								<div class="plus-horizontal"></div>
								<div class="plus-vertical"></div>
							</div>
							<div class="plus-icon">
								<div class="plus-horizontal"></div>
								<div class="plus-vertical"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<style>
	.hero {
		min-height: 100vh;
		background: #fbf8cc;
		padding: 6rem 0 4rem 0;
		display: flex;
		align-items: center;
	}

	.container {
		max-width: 1200px;
		margin: 0 auto;
		padding: 0 2rem;
		width: 100%;
	}

	.hero-content {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 4rem;
		align-items: center;
	}

	.hero-text {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.greeting {
		font-family: 'Poppins', sans-serif;
		font-weight: 500;
		font-size: 1.75rem;
		color: #03045e;
		margin: 0;
		line-height: 1.5;
	}

	.title {
		font-family: 'Poppins', sans-serif;
		font-weight: 800;
		font-size: 6.25rem;
		color: #03045e;
		margin: 0;
		line-height: 1.16;
	}

	.location {
		font-family: 'Poppins', sans-serif;
		font-weight: 500;
		font-size: 1.75rem;
		color: #03045e;
		margin: 0 0 2rem 0;
		line-height: 1.5;
	}

	.decorative-bars {
		display: flex;
		gap: 0.5rem;
		margin: 2rem 0;
	}

	.bar {
		width: 16px;
		height: 29px;
		background: #474306;
		border-radius: 6px;
	}

	.hero-image {
		display: flex;
		justify-content: center;
		position: relative;
	}

	.image-container {
		position: relative;
		max-width: 400px;
		width: 100%;
	}

	.image-container img {
		width: 100%;
		height: auto;
		border-radius: 12px;
		border: 1px solid #474306;
	}

	.decorative-elements {
		position: absolute;
		top: -20px;
		right: -20px;
	}

	.plus-icons {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 8px;
	}

	.plus-icon {
		position: relative;
		width: 24px;
		height: 24px;
		background: rgba(251, 248, 204, 0.9);
		border-radius: 6px;
		border: 1px solid #474306;
	}

	.plus-horizontal,
	.plus-vertical {
		position: absolute;
		background: #474306;
		border-radius: 6px;
	}

	.plus-horizontal {
		width: 24px;
		height: 6px;
		top: 50%;
		left: 0;
		transform: translateY(-50%);
	}

	.plus-vertical {
		width: 6px;
		height: 24px;
		left: 50%;
		top: 0;
		transform: translateX(-50%);
	}

	@media (max-width: 1024px) {
		.title {
			font-size: 5rem;
		}
	}

	@media (max-width: 768px) {
		.hero {
			padding: 5rem 0 3rem 0;
		}

		.container {
			padding: 0 1rem;
		}

		.hero-content {
			grid-template-columns: 1fr;
			gap: 3rem;
			text-align: center;
		}

		.greeting,
		.location {
			font-size: 1.5rem;
		}

		.title {
			font-size: 3.5rem;
		}

		.decorative-bars {
			justify-content: center;
		}

		.decorative-elements {
			top: -15px;
			right: -15px;
		}

		.plus-icon {
			width: 20px;
			height: 20px;
		}

		.plus-horizontal {
			width: 20px;
			height: 5px;
		}

		.plus-vertical {
			width: 5px;
			height: 20px;
		}
	}
</style>
