// generationBenchFrontend/simple/ByClaude4Sonnet/svelteKit/directMethod/src/lib/components/Contact.svelte
<script lang="ts">
	import contactImage from '$lib/assets/contact-image.png';

	interface ContactInfo {
		type: string;
		value: string;
		link?: string;
	}

	const contactData: ContactInfo[] = [
		{
			type: "email",
			value: "johndoe@mail.com",
			link: "mailto:johndoe@mail.com"
		},
		{
			type: "twitter",
			value: "twitter.com/johndoe",
			link: "https://twitter.com/johndoe"
		},
		{
			type: "behance",
			value: "behance.com/johndoe",
			link: "https://behance.com/johndoe"
		}
	];
</script>

<section id="contact" class="contact">
	<div class="container">
		<div class="contact-content">
			<div class="contact-image">
				<img src={contactImage} alt="Contact" />
			</div>
			
			<div class="contact-info">
				<h2 class="section-title">contact.</h2>
				
				<p class="description">
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. 
					Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam.
				</p>
				
				<div class="contact-list">
					{#each contactData as contact}
						<div class="contact-item">
							{#if contact.link}
								<a href={contact.link} class="contact-link">
									{contact.value}
								</a>
							{:else}
								<span class="contact-value">{contact.value}</span>
							{/if}
						</div>
					{/each}
				</div>
			</div>
		</div>
	</div>
</section>

<style>
	.contact {
		background: #fbf8cc;
		padding: 6rem 0;
	}

	.container {
		max-width: 1200px;
		margin: 0 auto;
		padding: 0 2rem;
	}

	.contact-content {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 4rem;
		align-items: start;
	}

	.contact-image {
		width: 100%;
		height: 400px;
		overflow: hidden;
		border-radius: 8px;
	}

	.contact-image img {
		width: 100%;
		height: 100%;
		object-fit: cover;
		border-radius: 8px;
	}

	.contact-info {
		display: flex;
		flex-direction: column;
		gap: 2rem;
	}

	.section-title {
		font-family: 'Poppins', sans-serif;
		font-weight: 800;
		font-size: 6.25rem;
		color: #f7f197;
		margin: 0;
		line-height: 1.16;
	}

	.description {
		font-family: 'Poppins', sans-serif;
		font-weight: 400;
		font-size: 1.5rem;
		color: #03045e;
		line-height: 1.833;
		margin: 0;
		max-width: 640px;
	}

	.contact-list {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.contact-item {
		display: flex;
		align-items: center;
	}

	.contact-link,
	.contact-value {
		font-family: 'Poppins', sans-serif;
		font-weight: 400;
		font-size: 1.5rem;
		color: #03045e;
		line-height: 1.833;
		text-decoration: none;
		transition: color 0.3s ease;
	}

	.contact-link:hover {
		color: #474306;
		text-decoration: underline;
	}

	@media (max-width: 1024px) {
		.section-title {
			font-size: 5rem;
		}
	}

	@media (max-width: 768px) {
		.contact {
			padding: 4rem 0;
		}

		.container {
			padding: 0 1rem;
		}

		.contact-content {
			grid-template-columns: 1fr;
			gap: 3rem;
		}

		.section-title {
			font-size: 3.5rem;
		}

		.description {
			font-size: 1.25rem;
		}

		.contact-link,
		.contact-value {
			font-size: 1.25rem;
		}

		.contact-image {
			height: 300px;
		}
	}
</style>

// nextjsFrontend/directmethod/components/sections/Contact.tsx
import Image from 'next/image';

export default function Contact() {
  const contactInfo = [
    {
      type: "email",
      label: "johndoe@mail.com",
      href: "mailto:johndoe@mail.com"
    },
    {
      type: "twitter",
      label: "twitter.com/johndoe", 
      href: "https://twitter.com/johndoe"
    },
    {
      type: "behance",
      label: "behance.com/johndoe",
      href: "https://behance.net/johndoe"
    }
  ];

  return (
    <section id="contact" className="py-16 px-8 bg-light-yellow">
      <div className="max-w-7xl mx-auto">
        {/* Section title */}
        <h2 className="text-6xl md:text-8xl lg:text-9xl font-extrabold text-too-light-yellow mb-12">
          contact.
        </h2>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
          {/* Contact info */}
          <div className="space-y-8">
            <p className="text-xl md:text-2xl text-dark-blue leading-relaxed">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet vulputate tristique quam felis. 
              Id phasellus dui orci vulputate consequat nulla proin. Id sit scelerisque neque, proin bibendum diam.
            </p>
            
            <div className="space-y-4">
              {contactInfo.map((contact, index) => (
                <div key={index}>
                  <a 
                    href={contact.href}
                    target={contact.type !== 'email' ? '_blank' : undefined}
                    rel={contact.type !== 'email' ? 'noopener noreferrer' : undefined}
                    className="text-xl text-dark-blue hover:text-dark-brown transition-colors leading-relaxed"
                  >
                    {contact.label}
                  </a>
                </div>
              ))}
            </div>
          </div>
          
          {/* Contact image */}
          <div className="flex justify-center lg:justify-end">
            <div className="relative w-full max-w-md h-80 rounded-2xl overflow-hidden">
              <Image
                src="/images/contact-image.png"
                alt="Contact"
                fill
                className="object-cover"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
